### ISSUE TITLE
ha 0.99.3 [homeassistant.components.sensor] Updating baidu_face sensor took longer than the scheduled update interval 0:00:03

### ISSUE THREAD

**Issue by j1111011** [Caffreyfans/baidu_identity#1]
HA 0.99.3 版本识别不了，我在aip上申请了sn,key，但是配置之后，一直报这个错误：
2019-10-06 11:04:42 WARNING (MainThread) [homeassistant.components.sensor] Updating baidu_face sensor took longer than the scheduled update interval 0:00:03

偶尔还会报：

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aip.baidubce.com', port=443): Max retries exceeded with url: /rest/2.0/face/v3/search (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 441, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.homeassistant/custom_components/baidu_face/sensor.py", line 112, in update
    ret = self.face_searching(save_path)
  File "/root/.homeassistant/custom_components/baidu_face/sensor.py", line 166, in face_searching
    response = requests.post(url=request_url, headers=headers, data=data)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='aip.baidubce.com', port=443): Max retries exceeded with url: /rest/2.0/face/v3/search (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
/root/.homeassistant/deps/lib/python3.7/site-packages/zeep/asyncio/transport.py:61: RuntimeWarning: coroutine 'noop2' was never awaited
  self.session.connector.close()

我在百度控制台上，人脸识别那，成功请求为0.应该是没有链接上，求大佬适配。

**Comment by Caffreyfans** [comment]
好的，这个问题很多人也跟我提到了。该插件确实存在 HomeAssistant 通过 https 地址无法访问的问题，我会在一个月之内修复该插件的。还请等待一下，最近还有毕设要忙。理解万岁~我现在在做一个关于红外的项目，就是 IReasy 的升级版，目标用户也是 HomeAssistant 用户，有兴趣还请关注一下。
